"""empty message

Revision ID: 1b09c5faf5e
Revises: 4c5864e0578
Create Date: 2015-10-25 09:54:57.670797

"""

# revision identifiers, used by Alembic.
revision = '1b09c5faf5e'
down_revision = '4c5864e0578'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    ### end Alembic commands ###
