"""empty message

Revision ID: 487768bece6
Revises: 1b09c5faf5e
Create Date: 2015-10-25 02:38:09.108907

"""

# revision identifiers, used by Alembic.
revision = '487768bece6'
down_revision = '1b09c5faf5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('protein', sa.String(length=500), nullable=True),
    sa.Column('force_field', sa.String(length=500), nullable=True),
    sa.Column('engine', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent'], ['simulation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('sim_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('simulation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['simulation'], ['simulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sim_file')
    op.drop_table('simulation')
    ### end Alembic commands ###
